# service.yaml
apiVersion: v1
kind: Service
metadata:
  # 여기에 정의한 서비스의 이름을 StatefulSet 에 연결해야 한다 
  name: headless-svc
spec:
  selector:
    app: stateful-nginx
  # clusterIP: None 의 이미는  ip 를 할당하지 않고 Loadbalancing 을 하지 않겠다는 의미
  # 단지 selector 에 부합하는 StatefulSet 의 단일 진입점 역활만 하겠다 
  # clusterIP: None 되어 있는 서비스를 headless 서비스라고 부른다.
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
  