# step06_pod_volume/volume.yaml
apiVersion: v1
kind: Pod
metadata:
  name: real-shared-pod
spec:
  containers:
  - name: web-container
    image: nginx:latest
    # volume 연결
    volumeMounts:
    - name: shared-storage # 아래에 정의한 volume 의 이름 
      mountPath: /web-data # container 안에서의 경로 
  - name: log-container
    image: busybox:1.28
    # 지속적으로 동작하도록 동작 추가하기 (sleep 을 무한루프로 실행하도록 한다)
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: shared-storage
      mountPath: /log-data
  volumes:
  - name: shared-storage
    emptyDir: {} # 빈 object 를 전달해서 빈 volume 이 만들어 지도록 한다 
